#!/bin/bash

qemu-system-riscv64     -machine virt \
                        -s \
                        -nographic \
                        -bios fw/fw_dynamic.bin \
                        -kernel kernel.elf
